sudo: false
language: python
cache: pip

script:
  - tox

install:
  - pip install tox

matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36-django111
    - python: "3.5"
      env: TOXENV=py35-django21
    - python: "3.6"
      env: TOXENV=py36-django21
    - python: "nightly"
      env: TOXENV=py37-django21
    - python: "3.6"
      env: TOXENV=lint

notifications:
  email: false
  irc: "irc.freenode.org#XelNext"
